### ISSUE TITLE
Any plan to support mysql?

### ISSUE THREAD

**Issue by Yansongsongsong** [muehlemann-popp/django-materialized-view#1]
From the implementation, it seems to support pg only.

do we have any plan to support mysql?

**Comment by Sheripov** [comment]
Welcome @Yansongsongsong. As far as I know, MySQL still doesn't support materialized view. [A.6.5.](https://dev.mysql.com/doc/refman/8.0/en/faqs-views.html)

**Comment by Sheripov** [comment]
@Yansongsongsong If you know some workaround here feel free to suggest it.
